### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by brihogan** [arcbtc/LNURLPoS#10]
This isn’t an issue. Just not sure if I can send messages in GitHub. Really just wanted to say thank you for such a cool project. You’re doing such cool stuff and it’s so cool that you’re being open about it and letting everyone have the code and even show them in a video how it all works. So cool!

I had a pet project a few years back related to Ninja Warrior-type timing for a local business. It was such a fun hobby and seeing your work makes me get back that excitement. Now my mind is racing thinking about doing something with your project with something like an arcade, vending machine, art-piece, etc. Those things have been hampered in my mind due to lack of internet connection in some locations (and paying for cell access was not worth it).

I think with your system the vendor has to look at a customer’s phone to see the pin code, right? Could that pin code be replaced by a QR code and then the arcade/vending-machine has a camera that confirms the code? That way everything could be totally unmanned, right?

Anyway, now I have to think up a project. My wife will probably be mad at you. :)

Thanks again!

**Comment by arcbtc** [comment]
Absolutely. I have been speaking with an excellent/small/cheap vending machine supplier in China to make such a thing possible. As soon as it arrives I will release a tut

**Comment by EastSideTony** [comment]
Excellent

**Comment by arcbtc** [comment]
https://github.com/arcbtc/LNURLVend
