### ISSUE TITLE
Which chip and memory is needed on the TTGO

### ISSUE THREAD

**Issue by bitcoina** [arcbtc/LNURLPoS#3]
Love your work Ben...

The link to the TTGO actually has 4 options (2 different chips and memory choices)

Can you advise which one is needed (or if it doesn't matter). Thanks

Options are

- ch9102f chip (4 & 16 mb)
- ch340k chip (4 & 16 mb)

**Comment by CmdrPenetrant** [comment]
+1

**Comment by arcbtc** [comment]
`ch9102f chip (4 & 16 mb)` is best

**Comment by bitcoina** [comment]
Awesome.  Thanks!
