### ISSUE TITLE
Connecting a Lightning Network PoS to LoRaWAN

### ISSUE THREAD

**Issue by tobias-kaiser** [arcbtc/LNURLPoS#4]
Interesting work. I think it's a good step towards offline payments, but it still requires the customer to have connectivity. I'm looking for a system that enables payments in the case of an emergency, such as a large-scale blackout. LoRaWAN networks (e.g. Helium) would be a perfect technology to create a fail-safe method for connecting, since these devices don't require much power and can easily be kept online by emergency generators. 

So my idea would be a PoS that is connected to LoRaWAN and does not require the customer to have connectivity. The payment workflow would then look like this:

1. The merchant enters the payment amount and creates a LN invoice.
2. The merchant sends the invoice to the customer, who signs it and sends the signed message back to the PoS.
3. The PoS uses its LoRaWAN connectivity to send the signed message off.

I'm wondering if this is somehow possible?

**Comment by arcbtc** [comment]
Probably, although you would have to get wallets to implement, which would be tricky. 
The payer could create an LNURL-withdraw offline, give it to the merchant who sends it over lora, then gets a confirmation back when paid, but again you would need the customers to be able to mint LNURL-Withdraws, a javacard system could do such magic
