### ISSUE TITLE
LRURL Pay Error

### ISSUE THREAD

**Issue by Ganzosupremo** [arcbtc/LNURLPoS#7]
The PoS have been working just fine, but recently, when I wanted to do another, this new one doesn't work.
Everything is fine, the keypad woks, the display works, but there's seems to be a problem with the QRcode.
 The display shows the QRcode but when I scanned it with a LN wallet it shows this error: ¨An error occurred while attempting to retrieve an invoice from demo.lnbits.com! Reason: Invalid character '<' 
This is in Breez but the same happens with other wallets, they say "invalid character '<' ".
And when you try to pay with Muun wallet it doesn't even let you pay, it says: "This seems like a LNURL code. It allows you to receive bitcoin via lightning, instead of sending it. Do you want to use it?" But I think that's a different issue.
If someone knows what that character means or how to fix it, please let me know. I really wanna use this PoS for accepting Bitcoin payments in my business.

**Comment by arcbtc** [comment]
We changed to legend.lnbits.com
